create table if not exists public.chat_messages (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    display_name text not null check (char_length(display_name) between 1 and 24),
    display_color text not null default '#dcf2ff' check (display_color ~ '^#[0-9a-fA-F]{6}$'),
    body text not null check (char_length(body) between 1 and 500),
    created_at timestamptz not null default now()
);

alter table public.chat_messages
    add column if not exists display_color text not null default '#dcf2ff';

create index if not exists chat_messages_created_at_idx
    on public.chat_messages (created_at desc);

alter table public.chat_messages enable row level security;

revoke all on table public.chat_messages from anon, authenticated;
grant select, insert on table public.chat_messages to authenticated;
grant usage, select on sequence public.chat_messages_id_seq to authenticated;

drop policy if exists "Public chat is readable" on public.chat_messages;
create policy "Public chat is readable"
    on public.chat_messages for select
    to authenticated
    using (true);

drop policy if exists "Anonymous visitors can send as themselves" on public.chat_messages;
create policy "Anonymous visitors can send as themselves"
    on public.chat_messages for insert
    to authenticated
    with check (
        (select auth.uid()) = user_id
        and char_length(display_name) between 1 and 24
        and char_length(body) between 1 and 500
    );

do $$
begin
    if not exists (
        select 1 from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'chat_messages'
    ) then
        alter publication supabase_realtime add table public.chat_messages;
    end if;
end $$;
