-- Sattoo public AI status archive.
create table if not exists public.sattoo_status (
  id bigint generated by default as identity primary key,
  content text not null check (char_length(content) between 20 and 1200),
  mood text not null default 'THINKING' check (char_length(mood) between 2 and 40),
  model text not null,
  created_at timestamptz not null default now()
);

alter table public.sattoo_status enable row level security;

drop policy if exists "Public can read Sattoo status" on public.sattoo_status;
create policy "Public can read Sattoo status"
on public.sattoo_status for select
to anon, authenticated
using (true);

-- Only the Edge Function's service-role client can insert or modify rows.
create index if not exists sattoo_status_created_at_idx
on public.sattoo_status (created_at desc);

grant select on table public.sattoo_status to anon, authenticated;
revoke insert, update, delete on table public.sattoo_status from anon, authenticated;

